echo "How many data do you want to write?"

read times

for ((i = 1; i <= times; i++))
do
   echo $i
   echo "NyUZmkPEAEfchhnOpcadHQzFkEfJYIelwBUFKRFrDviZSMOKCjEiXkVkyPjigTgybUlhIyDJNzgEPeAIjkBrsoVRyjPrsDmULAsOwlcUBUPHtwCyTjwfJEcKhFMAVyiarEaWfpMfkBfFdjJnJDxUGaOtjIypOcUlqruEpYCiDLHViGdscliaEiVXdsGxyNhPuqMZkgKJEGlMNqlfXeGnryCtybevTmaAwpAylzNWxhmUgoLFNRYKnAZSWHWJqvghomZnCodFfPooGrYIUDoTWIgOaEUHUaYmNNBytsTMGQARJFNPeQoBUuZkdXBsTwwmGhkHQkjMSIuorDMgsHxyIttacRehFzzDTcJiMrxsQlCjCcvWnndvNjUgeWRWUVJrMtPPqZBeSwfDLwyIldKNTlrdfASlNpSvnKtCGEhhZKJjcuaWGCeEaRPInoTcsZJOAsZLnflLTeCeVPcEXteVxBHFTVHAwKYWwpuoikYhGNmrwiuSjomFmbriKMlrupa" > /tmp/ssd/ssd_file
   wait
done